version: '3.8'

services:
  mosquitto:
    build: .
    container_name: Mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
